# Use postgres/example user/password credentials
version: '3.1'

services:
  octoprint:
    image: octoprint/octoprint
    restart: always
    environment:
      ENABLE_MJPG_STREAMER: 'false'
    ports:
      - "80:80"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - octoprint:/octoprint

volumes:
  octoprint:
