# Use postgres/example user/password credentials
version: '3.9'

services:
  octoprint:
    image: octoprint/octoprint
    restart: always
    environment:
      ENABLE_MJPG_STREAMER: 'false'
    ports:
      - "8080:80"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - octoprint:/octoprint
    privileged: true

volumes:
  octoprint:
